name: Build APK - Debug Biasa

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Nama Project'
        required: true
        default: 'MyApp'

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK Debug
        run: flutter build apk --debug

      - name: Rename APK
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-debug.apk output/${{ github.event.inputs.project_name }}-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.project_name }}-debug
          path: output/*.apk
          retention-days: 7
